test for link bug
sysctstage/OpenSSL pull request #33
Opened 2018-11-20 01:56 UTC by kewenchao

Tracked-On: OAM-66564
Signed-off-by: shenya1x yangx.shen@intel.com

2018-11-20 02:43 UTC, kewenchao111 approved these changes

2018-11-20 02:50 UTC, kewenchao111 requested changes
need change

2018-11-20 02:52 UTC, kewenchao111 approved these changes

2018-11-26 02:17 UTC, geyanfax approved these changes

2018-11-27 03:22 UTC, sysctstage reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-staging/builders/opensource-preintegration/builds/217

2018-11-27 03:23 UTC, closed without merging